### ISSUE TITLE
SCPP fails with samtools 1.10

### ISSUE THREAD

**Issue by SilasK** [Shamir-Lab/SCAPP#6]
error:

```
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --verbosity INT
               Set level of verbosity
```

**Comment by dpellow** [comment]
@SilasK thanks for reporting this! Can you please specify the issue further? What command did you use to run SCAPP? Where does the error occur and what is the error message?

**Comment by dpellow** [comment]
Fixed this

**Comment by SilasK** [comment]
I still get the error with samtools v1.9 :-(

I run the following command: 

```
scapp -g $sample/assembly/K$K/assembly_graph.fastg \
 -o $sample/plasmids -k $K -p 8 \
 -r1 $sample/sequence_quality_control/${sample}_QC_R1.fastq.gz \
 -r2 $sample/sequence_quality_control/${sample}_QC_R2.fastq.gz
```

and the scapp log:

```
23/01/2020 15:44: Beginning SCAPP workflow
23/01/2020 15:44: Got parameters:
        Input graph: S001/assembly/K99/assembly_graph.fastg
        Output directory: S001/plasmids
        Maximum k value: 99
        # processes: 8
        Maximum CV: 0.5
        Minimum Length: 1000
        Bamfile: None
        Reads file 1: S001/sequence_quality_control/S001_QC_R1.fastq.gz
        Reads file 2: S001/sequence_quality_control/S001_QC_R2.fastq.gz
        Use scores: True
        Use genes: True
        Path to BWA executables:
        Path to NCBI executables:
        Path to samtools executables:
        PlasClass scores file: None
23/01/2020 15:44: Creating fasta from fastg
23/01/2020 15:44: Creating BAM file
23/01/2020 15:44: Executing command: 'bwa index S001/plasmids/intermediate_files/assembly_graph.nodes.fasta'
23/01/2020 16:00: Executing command: 'bwa mem -t 8 S001/plasmids/intermediate_files/assembly_graph.nodes.fasta S001/sequence_quality_control/S001_QC_R1.fastq.gz S001/sequence_quality_control/S001_QC_R2.fastq.gz | samtools  view -buS -@ 7 - > S001/plasmids/intermediate_files/reads_pe.bam'
23/01/2020 16:50: Executing command: 'samtools view -bF 0x0900 -@ 7 S001/plasmids/intermediate_files/reads_pe.bam > S001/plasmids/intermediate_files/reads_pe_primary.bam'
23/01/2020 16:51: Executing command: 'samtools sort S001/plasmids/intermediate_files/reads_pe_primary.bam S001/plasmids/intermediate_files/reads_pe_primary.sort'

```

I can try to install v1.19 but It's probably better to specify the temp folder

**Comment by dpellow** [comment]
@SilasK Can you please pull the fix and recreate the conda env with the latest install_scapp.yaml and let us know if this problem continues.
Thanks

**Comment by SilasK** [comment]
It was fixed the problem with samtools. I did't see you made a new version.

**Comment by SilasK** [comment]
I use this issue to give notice of another warning during plasclass:

```/home/kiesers/scratch/miniconda3/envs/scapp/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
```

You have to define which version you want to use.

**Comment by dpellow** [comment]
@SilasK For some reason the error message isn't showing up in your comment - can you repost it or send to my email: dpellow AT post DOT tau DOT ac DOT il
Thanks
